"""
extractor/gazetteer.py — Maintained reference set of known threat-intel names.

This replaces the "reject if on a hand-grown denylist" approach with "accept if
it matches a maintained reference set of *known-good* entities (or has entity
shape)".  The reference set is a bundled snapshot of public taxonomies (MITRE
ATT&CK via MISP galaxy + MISP threat-actor / ransomware / malware clusters),
regenerated by ``scripts/update_gazetteer.py``.

Matching is done on a canonical key (casefold + strip separators + drop
non-alphanumerics) so "Cobalt Strike", "cobalt-strike" and "CobaltStrike" all
resolve to the same entry, matching the canonicalisation used by
``extractor.normalizer.canonicalize_entity_value`` for name types.

Never raises: if the snapshot is missing the sets are empty and every lookup
returns ``False`` — the shape checker then carries the accept/reject decision on
its own, so extraction degrades gracefully rather than breaking.

Public interface
----------------
is_known_actor(name)       → bool
is_known_malware(name)     → bool
is_known_ransomware(name)  → bool
is_known(name, category)   → bool   (category in {"threat_actor","malware","ransomware"})
category_of(name)          → str | None
stats()                    → dict
"""

from __future__ import annotations

import json
import logging
import os
import re
import unicodedata
from typing import Optional

logger = logging.getLogger(__name__)

_DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "threat_gazetteer.json",
)

# Minimum canonical-key length — drops junk snapshot entries like "$$$" (which
# canonicalise to "") or single stray characters that would over-match.
_MIN_KEY_LEN = 2

_loaded = False
_actors: frozenset[str] = frozenset()
_malware: frozenset[str] = frozenset()
_ransomware: frozenset[str] = frozenset()
_generated_at: Optional[str] = None


def _canonical_key(name: str) -> str:
    """Canonical lookup key — must mirror normalizer canonicalisation for
    THREAT_ACTOR_HANDLE / MALWARE_FAMILY / RANSOMWARE_GROUP so an extracted
    entity's canonical value lines up with a gazetteer entry."""
    if not name:
        return ""
    v = unicodedata.normalize("NFKD", name)
    v = v.encode("ascii", "ignore").decode("ascii")
    v = v.lower()
    v = re.sub(r"[\s\-_.]", "", v)
    v = re.sub(r"[^\w]", "", v)
    return v


def _keyset(names) -> frozenset[str]:
    out: set[str] = set()
    for n in names or []:
        k = _canonical_key(n)
        if len(k) >= _MIN_KEY_LEN:
            out.add(k)
    return frozenset(out)


def _load() -> None:
    global _loaded, _actors, _malware, _ransomware, _generated_at
    if _loaded:
        return
    _loaded = True
    try:
        with open(_DATA_PATH, encoding="utf-8") as fh:
            data = json.load(fh)
        _actors = _keyset(data.get("threat_actors"))
        _malware = _keyset(data.get("malware"))
        _ransomware = _keyset(data.get("ransomware"))
        _generated_at = data.get("generated_at")
        logger.info(
            "Gazetteer loaded: %d actors, %d malware, %d ransomware (generated %s)",
            len(_actors), len(_malware), len(_ransomware), _generated_at,
        )
    except FileNotFoundError:
        logger.warning(
            "Gazetteer snapshot not found at %s — shape checks will run without "
            "the known-good reference set. Regenerate with "
            "scripts/update_gazetteer.py.",
            _DATA_PATH,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("Failed to load gazetteer (non-fatal): %s", exc)


def is_known_actor(name: str) -> bool:
    _load()
    return _canonical_key(name) in _actors


def is_known_malware(name: str) -> bool:
    _load()
    return _canonical_key(name) in _malware


def is_known_ransomware(name: str) -> bool:
    _load()
    return _canonical_key(name) in _ransomware


def is_known(name: str, category: str) -> bool:
    if category in ("threat_actor", "THREAT_ACTOR_HANDLE", "actor"):
        return is_known_actor(name)
    if category in ("malware", "MALWARE_FAMILY"):
        return is_known_malware(name)
    if category in ("ransomware", "RANSOMWARE_GROUP"):
        return is_known_ransomware(name)
    return False


def category_of(name: str) -> Optional[str]:
    """Return the most specific known category for *name*, or None."""
    _load()
    key = _canonical_key(name)
    if key in _ransomware:
        return "ransomware"
    if key in _malware:
        return "malware"
    if key in _actors:
        return "threat_actor"
    return None


def stats() -> dict:
    _load()
    return {
        "actors": len(_actors),
        "malware": len(_malware),
        "ransomware": len(_ransomware),
        "generated_at": _generated_at,
    }
